export const hotCryptos = [
  {
    id: 1,
    name: "TREEINCAT",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/34570.png",
    price: "$0.0009266",
    change: "9.18%",
    positon: true,
  },
  {
    id: 2,
    name: "CORE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/23254.png",
    price: "$0.4867",
    change: "23.77%",
    positon: false,
  },
  {
    id: 3,
    name: "ALPACA",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/8707.png",
    price: "$0.05716",
    change: "15.13%",
    positon: true,
  },
  {
    id: 4,
    name: "EOS",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png",
    price: "$0.5937",
    change: "8.63%",
    positon: false,
  },
  {
    id: 5,
    name: "X",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/33108.png",
    price: "$0.00007616",
    change: "17.25%",
    positon: true,
  },
];

export const recentCrypto = [
  {
    id: 1,
    name: "GHIBLIAI",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36165.png",
    price: 0.0113585,
    change: 0.21,
    priceDisplay: "$0.0113585",
    changeDisplay: "0.21%",
    positon: false,
  },
  {
    id: 2,
    name: "CORN",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36164.png",
    price: 0.05663,
    change: 2.29,
    priceDisplay: "$0.05663",
    changeDisplay: "2.29%",
    positon: true,
  },
  {
    id: 3,
    name: "ABSIMPSON",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36162.png",
    price: 0.0129295,
    change: 127.44,
    priceDisplay: "$0.0129295",
    changeDisplay: "127.44%",
    positon: false,
  },
  {
    id: 4,
    name: "AICE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36161.png",
    price: 0.9376,
    change: 0.91,
    priceDisplay: "$0.9376",
    changeDisplay: "0.91%",
    positon: false,
  },
  {
    id: 5,
    name: "ANNE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36160.png",
    price: 0.0001458,
    change: 46.35,
    priceDisplay: "$0.0001458",
    changeDisplay: "46.35%",
    positon: true,
  },
];

export const mostVisitedCypto = [
  {
    id: 1,
    name: "BTC",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    price: 82607.79,
    priceDisplay: "$82,607.79",
    change: 0.01,
    changeDisplay: "0.01%",
    changeType: "neutral",
    positon: true,
  },
  {
    id: 2,
    name: "ICE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/27650.png",
    price: 0.003519,
    priceDisplay: "$0.003519",
    change: 0.43,
    changeDisplay: "0.43%",
    changeType: "positive",
    positon: true,
  },
  {
    id: 3,
    name: "XRP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
    price: 2.13,
    priceDisplay: "$2.13",
    change: 0.84,
    changeDisplay: "0.84%",
    changeType: "positive",
    positon: false,
  },
  {
    id: 4,
    name: "PI",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/35697.png",
    price: 0.7689,
    priceDisplay: "$0.7689",
    change: 4.23,
    changeDisplay: "4.23%",
    changeType: "positive",
    positon: true,
  },
  {
    id: 5,
    name: "ETH",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    price: 1816.92,
    priceDisplay: "$1,816.92",
    change: 0.14,
    changeDisplay: "0.14%",
    changeType: "positive",
    positon: false,
  },
];
export const CommunityVotes = [
  {
    id: 1,
    name: "BTC",

    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    price: 82607.79,
    priceDisplay: "$82,607.79",
    change: 0.01,
    changeDisplay: "0.01%",
    changeType: "neutral",
    positon: true,
    fullName: "Bitcoin",
    up: 232,
    down: 89,
  },
  {
    id: 2,
    name: "ICE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/27650.png",
    price: 0.003519,
    priceDisplay: "$0.003519",
    change: 0.43,
    changeDisplay: "0.43%",
    changeType: "positive",
    positon: true,
    fullName: "True Ice",
    up: 2232,
    down: 9,
  },
  {
    id: 3,
    name: "XRP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
    price: 2.13,
    priceDisplay: "$2.13",
    change: 0.84,
    changeDisplay: "0.84%",
    changeType: "positive",
    positon: false,
    fullName: "Ripple",
    up: 201,
    down: 8,
  },
  {
    id: 4,
    name: "PI",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/35697.png",
    price: 0.7689,
    priceDisplay: "$0.7689",
    change: 4.23,
    changeDisplay: "4.23%",
    changeType: "positive",
    positon: true,
    fullName: "Pi Network",
    up: 508,
    down: 90,
  },
  {
    id: 5,
    name: "ETH",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    price: 1816.92,
    priceDisplay: "$1,816.92",
    change: 0.14,
    changeDisplay: "0.14%",
    changeType: "positive",
    positon: false,
    fullName: "Ethereum",
    up: 6002,
    down: 19,
  },
];

export const productsMenu = {
  products: [
    {
      name: "Converter",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuConverterIcon.svg",
      link: false,
    },
    {
      name: "Newsletter",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuNewsIcon.svg",
      link: true,
    },
    {
      name: "CMC Labs",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuExplorerIcon.svg",
      link: true,
    },
    {
      name: "Telegram Bot",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuTelegramBotIcon.svg",
      link: true,
    },
    {
      name: "Advertise",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuAdvertiseIcon.svg",
      link: true,
    },
  ],
  other: [
    {
      name: "Crypto API",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCryptoApiIcon.light.svg",
      link: true,
    },
    {
      name: "Site Widgets",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuWidgetsIcon.light.svg",
      link: false,
    },
  ],
  campaigns: [
    {
      name: "Airdrops",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuAirdropsIcon.svg",
      link: false,
    },
    {
      name: "Diamond Rewards",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuRewardsIcon.svg",
      link: false,
    },
    {
      name: "Learn & Earn",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuEarnCryptoIcon.svg",
      link: true,
    },
  ],
  calendars: [
    {
      name: "ICO Calendar",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuICOIcon.svg",
      link: false,
    },
    {
      name: "Events Calendar",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuEvents2Icon.svg",
      link: false,
    },
  ],
  learn: [
    {
      name: "News",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuNewsIcon.svg",
      link: false,
    },
    {
      name: "Academy",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuAlexandriaIcon.svg",
      link: true,
    },
    {
      name: "Research",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCMCResearch.svg",
      link: true,
    },
    {
      name: "Videos",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuVideosIcon.svg",
      link: true,
    },
    {
      name: "Glossary",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuGlossaryIcon.svg",
      link: true,
    },
  ],
};

export const cryptoCurrenciesMenu = {
  cryptocurrencies: [
    {
      name: "Ranking",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCmcIconV3.svg",
      link: false,
    },
    {
      name: "Categories",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCategoriesIconV3.svg",
      link: false,
    },
    {
      name: "Historical Snapshots",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuHistoryIconV3.svg",
      link: false,
    },
    {
      name: "Token unlocks",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuTokenUnlocksIconV2.svg",
      link: false,
    },
    {
      name: "Yield",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuYieldIconV2.svg",
      link: false,
    },
  ],
  Leaderboards: [
    {
      name: "Trending",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCmcIconV3.svg",
      link: false,
    },
    {
      name: "Upcoming",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuUpcomingIconV3.svg",
      link: false,
    },
    {
      name: "Recently Added",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuRecentlyAddedIconV3.svg",
      link: false,
    },
    {
      name: "Gainers & Losers",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuGainersLosersIconV3.svg",
      link: false,
    },
    {
      name: "Most Visited",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuMostVisitedV3.svg",
      link: false,
    },
    {
      name: "Community Sentiment",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCommunitySentiment.svg",
      link: false,
    },
    {
      name: "Chain Ranking",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuChainRankingV4.svg",
      link: false,
    },
  ],
  MarketOverview: [
    {
      name: "Market Overview",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuMarketOverviewIcon.svg",
      link: false,
    },
    {
      name: "CoinMarketCa 100 Index",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCMC100Icon.svg",
      link: false,
    },
    {
      name: "Fear and Greed Index",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuFearGreedIndexIcon.svg",
      link: false,
    },
    {
      name: "Altcoin Season Index",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuAltcoinIndexIcon.svg",
      link: false,
    },
    {
      name: "Bitcoin Dominance",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuBitcoinDominance.svg",
      link: false,
    },
    {
      name: "Crypto ETFs",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuBitcoinETFsIconV3.svg",
      link: false,
    },
  ],
  nft: [
    {
      name: "Overall NFT Stats",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuNFTOverviewV3.svg",
      link: false,
    },
    {
      name: "Upcoming Sales",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuUpcomingSales.svg",
      link: false,
    },
  ],
};

export const exchangesMenu = {
  centralized: [
    {
      name: "Spot",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuSpotIcon.svg",
      link: false,
    },
    {
      name: "Derivatives",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuDerivativesIcon.svg",
      link: false,
    },
  ],
  decentralized: [
    {
      name: "Spot",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuDexSpotIcon.svg",
      link: false,
    },
    {
      name: "Derivatives",
      img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuDexDerivativesIcon.svg",
      link: false,
    },
  ],
};

export const dexScanMenu = [
  {
    name: "New Pairs",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuMarketOverviewIcon.svg",
    link: false,
  },
  {
    name: "Trending Pairs",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCMC100Icon.svg",
    link: false,
  },

  {
    name: "Meme Explorer",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuBitcoinDominance.svg",
    link: false,
  },
  {
    name: "Gainers and Losers",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuBitcoinETFsIconV3.svg",
    link: false,
  },

  {
    name: "Community Votes",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuFearGreedIndexIcon.svg",
    link: false,
  },
  {
    name: "Top Traders",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuAltcoinIndexIcon.svg",
    link: false,
  },
];

export const community = [
  {
    name: "Feeds",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuVideosIcon.svg",
    link: true,
  },
  {
    name: "Topics",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuGlossaryIcon.svg",
    link: true,
  },
  {
    name: "Lives",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuNewsIcon.svg",
    link: false,
  },
  {
    name: "Articles",
    img: "https://s2.coinmarketcap.com/static/cloud/img/menu/MenuCMCResearch.svg",
    link: true,
  },
];

export const tableData = [
  {
    id: 1,
    name: "GHIBLIAI",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36165.png",
    price: 0.0113585,
    change: 0.21,
    priceDisplay: "$0.0113585",
    changeDisplay: "0.21%",
    positon: false,
    oneHour: -0.15,
    twentyFourHour: 1.32,
    sevenDay: 5.67,
    mcap: "300,987,654,321",
    vol: "120,123,456,789",
    cirsup: 45.23,
    graph: "/chart/long1.png",
    randomPercent: 92.45,
    ticker: "GHIB",
  },
  {
    id: 2,
    name: "CORN",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36164.png",
    price: 0.05663,
    change: 2.29,
    priceDisplay: "$0.05663",
    changeDisplay: "2.29%",
    positon: true,
    oneHour: 0.87,
    twentyFourHour: -1.22,
    sevenDay: 10.45,
    mcap: "500,765,432,109",
    vol: "250,234,567,890",
    cirsup: 78.9,
    graph: "/chart/red2.png",
    randomPercent: 48.76,
    ticker: "CORN",
  },
  {
    id: 3,
    name: "ABSIMPSON",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36162.png",
    price: 0.0129295,
    change: 127.44,
    priceDisplay: "$0.0129295",
    changeDisplay: "127.44%",
    positon: false,
    oneHour: -2.45,
    twentyFourHour: 5.32,
    sevenDay: -7.21,
    mcap: "150,543,210,987",
    vol: "90,345,678,912",
    cirsup: 32.14,
    graph: "/chart/long3.png",
    randomPercent: 75.34,
    ticker: "ABSIMP",
  },
  {
    id: 4,
    name: "AICE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36161.png",
    price: 0.9376,
    change: 0.91,
    priceDisplay: "$0.9376",
    changeDisplay: "0.91%",
    positon: false,
    oneHour: 1.11,
    twentyFourHour: -0.87,
    sevenDay: 4.32,
    mcap: "700,876,543,210",
    vol: "320,456,789,123",
    cirsup: 65.78,
    graph: "/chart/red4.png",
    randomPercent: 55.62,
    ticker: "AICE",
  },
  {
    id: 5,
    name: "ANNE",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36160.png",
    price: 0.0001458,
    change: 46.35,
    priceDisplay: "$0.0001458",
    changeDisplay: "46.35%",
    positon: true,
    oneHour: 0.56,
    twentyFourHour: 2.98,
    sevenDay: -3.87,
    mcap: "400,987,654,321",
    vol: "200,567,890,234",
    cirsup: 56.47,
    graph: "/chart/long5.png",
    randomPercent: 69.87,
    ticker: "ANNE",
  },
  {
    id: 6,
    name: "GHIBLIAI DUP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36165.png",
    price: 0.0135,
    change: 1.12,
    priceDisplay: "$0.0135",
    changeDisplay: "1.12%",
    positon: false,
    oneHour: 0.33,
    twentyFourHour: 2.45,
    sevenDay: 6.78,
    mcap: "310,876,543,210",
    vol: "130,678,901,234",
    cirsup: 46.89,
    graph: "/chart/red3.png",
    randomPercent: 47.23,
    ticker: "GHIB-DUP",
  },
  {
    id: 7,
    name: "CORN DUP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36164.png",
    price: 0.0598,
    change: 3.78,
    priceDisplay: "$0.0598",
    changeDisplay: "3.78%",
    positon: true,
    oneHour: -0.67,
    twentyFourHour: 1.98,
    sevenDay: 9.54,
    mcap: "520,765,432,109",
    vol: "260,789,012,345",
    cirsup: 79.45,
    graph: "/chart/long4.png",
    randomPercent: 54.89,
    ticker: "CORN-DUP",
  },
  {
    id: 8,
    name: "ABSIMPSON DUP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36162.png",
    price: 0.013,
    change: 120.54,
    priceDisplay: "$0.0130",
    changeDisplay: "120.54%",
    positon: false,
    oneHour: -1.98,
    twentyFourHour: 4.67,
    sevenDay: -6.32,
    mcap: "160,543,210,987",
    vol: "95,890,123,456",
    cirsup: 33.78,
    graph: "/chart/red1.png",
    randomPercent: 43.76,
    ticker: "ABS-DUP",
  },
  {
    id: 9,
    name: "AICE DUP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36161.png",
    price: 0.945,
    change: 1.78,
    priceDisplay: "$0.9450",
    changeDisplay: "1.78%",
    positon: false,
    oneHour: 1.56,
    twentyFourHour: -1.12,
    sevenDay: 5.78,
    mcap: "710,654,321,098",
    vol: "330,901,234,567",
    cirsup: 66.45,
    graph: "/chart/long2.png",
    randomPercent: 46.43,
    ticker: "AICE-DUP",
  },
  {
    id: 10,
    name: "ANNE DUP",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/36160.png",
    price: 0.0001495,
    change: 47.98,
    priceDisplay: "$0.0001495",
    changeDisplay: "47.98%",
    positon: true,
    oneHour: 0.89,
    twentyFourHour: 3.45,
    sevenDay: -2.98,
    mcap: "410,987,654,321",
    vol: "210,234,567,890",
    cirsup: 57.12,
    graph: "/chart/red5.png",
    randomPercent: 50.23,
    ticker: "ANNE-DUP",
  },
];
